# action.yml
name: 'Swagger Codegen'
description: 'Run Swagger Codegen with Github Actions'
branding:
    icon: code
    color: green
runs:
  using: 'docker'
  image: 'docker://swaggerapi/swagger-codegen-cli'